# Generated by Django 6.0.1 on 2026-02-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="title", max_length=200)),
                ("c_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("DONE", "Done"),
                            ("FAIL", "Fail"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "task_start_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "task_end_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("process_percent", models.IntegerField(max_length=3)),
                ("html", models.CharField(blank=True, default="")),
                ("error", models.CharField(blank=True, default="")),
            ],
        ),
    ]
