# Generated by Django 5.1.7 on 2026-02-10 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("c_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FAIL", "FAIL"),
                            ("PERMISSION_DENIED", "PERMISSION_DENIED"),
                            ("SUCCESS", "SUCCESS"),
                            ("PENDING", "PENDING"),
                            ("Q2_RUNNING", "Q2_RUNNING"),
                        ],
                        default=None,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "task_start_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "task_end_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "progress_percent",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "db_table": "user_logs",
            },
        ),
    ]
