# Generated by Django 6.0.1 on 2026-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlog",
            name="c_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
