# Generated by Django 6.0.1 on 2026-02-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_userlog_c_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlog",
            name="process_percent",
            field=models.IntegerField(default=None, max_length=3),
        ),
    ]
