# Generated by Django 6.0.1 on 2026-02-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_userlog_process_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlog",
            name="process_percent",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
